#Include, ..\classes\FilterLists.ahk
#Include, ..\classes\Settings.ahk
#Include, ..\classes\TrayControl.ahk
#Include, ..\classes\WindowHistory.ahk
#Include, ..\classes\WindowManager.ahk
#Include, ..\classes\WindowObject.ahk
#Include, ..\classes\XDListView.ahk
#Include, ..\classes\commands\CommandFactory.ahk
#Include, ..\classes\commands\CommandHandler.ahk
#Include, ..\classes\commands\CommandObject.ahk
#Include, ..\classes\commands\Commands.ahk
